#!/usr/bin/bash

notify() {
	notify-send -t 1500 "$1"
}

step=1
min_brightness=2.0
current_brightness=`xbacklight -get`
target_brightness=`python -c "print($current_brightness-$step)"`
j=`python -c "print($target_brightness >= $min_brightness)"`

if [[ "$j" = "True" ]]; then
	xbacklight -dec $step
else
    xbacklight -set $min_brightness
    notify "🚫  亮度已经足够低了!"
fi
