#!/usr/bin/env bash

notify() {
	notify-send -t 1500 "$1"
}

min_brightness=10
max_value=$(brightnessctl m)
step=$(echo "2*$max_value/100"|bc)
current_brightness=$(brightnessctl g)

case $1 in
	u)
		brightnessctl -q s "$step+"
		;;
	d)
		target_brightness=`echo "$current_brightness-$step" | bc`

		if [[ `echo "$target_brightness >= $min_brightness" | bc` -eq 1 ]]; then
			brightnessctl -q s "$step-"
		else
			brightnessctl -q s "$min_brightness"
			notify "🚫  亮度已经足够低了!"
		fi
		;;
	w)
		disp=`xrandr | grep -w connected | cut -f1 -d' '`
		# 调整为暖色调
		xbrightness.sh = $disp 0.4 --temp
		;;
	c)
		# 调整为冷色调
		disp=`xrandr | grep -w connected | cut -f1 -d' '`
		xbrightness.sh = $disp 0.6 --temp
		;;
	*)  ;;
esac

echo "$(brightnessctl g)" > $HOME/.brightness

sigdwmblocks 2
