#!/usr/bin/env bash

applist="$HOME/.cache/dmenu-applications"

[[ -f $applist ]] || {
    applist="$HOME/.cache/dmenu-applications-default"
}

[[ -f "$applist" ]] && {
    cat "$applist" | dmenu "$@" | ${SHELL:-"/bin/sh"} &
} || {
    dmenu_run "$@"
}
