#!/bin/sh

# 右键点击 dwm 标题栏的操作
# 1. 关闭窗口
# 2. 将窗口移到对应 tag

font="JetBrainsMono Nerd Font:style=medium:size=13"

options="取消\n关闭窗口\n移动窗口"

chosen=$(echo -e "$options" | dmenu $@ -fn "$font" -c -l 3)

if [[ "$chosen" = "关闭窗口" ]]; then
	dwmc killclient
elif [[ "$chosen" = "移动窗口" ]]; then
	tags="取消\n1\n2\n3\n4\n5\n6\n7\n8\n9\n"
	tag=$(echo -e "$tags" | dmenu $@ -fn "$font" -c -l 10)
	if [ "$tag" != "" ] && [ "$tag" != "取消" ] && [ $tag -ge 1 ] && [ $tag -le 9 ]; then
		dwmc tagex $((tag-1))
	fi
fi
